# YAML file for model config

setup:
    seed:
    - 34
    n_jobs:
    - 7
    file_paths:
        data_dir: './data/'
        allele_path: './data/FN_allele_clean_v2_20240319.csv'
    variables:
        filter_prov: 'Y'
        stratified: 'Y' 
        optim: 'GridSearch'
    test_size:
        - 0.2
        - 0.25
        - 0.3
    filter_threshold:
        - 2
        - 3
        - 5
    y_col:
        - Province
        - CombinedSites
        - CombinedSite2
    sampling_strategy:
        - SMOTE
        - SMOTEENN
        - random_upsampling
        - No_strat
    feat_eng: 
        - OHE
        - nzv
        - nzv_OHE
        - None
    feat_elim:
        - RFE
        - RFECV
        - None
    feat_elim_params:
        rfecv:
            n_step: 0.05
            min_features_select: 0.2
        rfe_proportion_list: [0.2, 0.4, 0.6, 0.8]
    models:
      Random_Forest: 
            model_type: 'Random Forest'
            param_grid:
                n_estimators: [100, 200, 300]
                max_depth: [10, 20, 30]
                min_samples_split: [2, 5, 10]
                min_samples_leaf: [1, 2, 4]
                criterion: ['gini', 'entropy']
            save_model_path: './output'
            results_path: './output/Output_template.csv'
      Logit_Boost:
            model_type: 'Logit Boost'
            param_grid:
                n_estimators: [50, 100, 150]
                learning_rate: [0.01, 0.1, 1]
            save_model_path: './output'
            results_path: './output/Output_template.csv'
      SVM: 
           model_type: 'SVM'
           param_grid:
               C: [0.1, 1, 10, 100]
               kernel: ['linear', 'poly', 'rbf', 'sigmoid']
               gamma: ['scale', 'auto']
           save_model_path: './output'
           results_path: './output/Output_template.csv'
      GBC:
           model_type: 'GradientBoostingClassifier'
           param_grid:
               n_estimators: [100, 200, 300]
               learning_rate: [0.01, 0.1, 0.5]
               max_depth: [3, 5, 7]
           save_model_path: './output'
           results_path: './output/Output_template.csv'
column_strains:
  Serovar: 
    Heidelberg: 'nzv_data/heidelberg'
    Enteritidis: 'nzv_data/enteritidis'
    Typhimurium: 'nzv_data/typhimurium'
    "I:4,[5],12:i:-": 'nzv_data/4512i'
    Infantis: 'nzv_data/infantis'
    Kentucky: 'nzv_data/kentucky'
    All: 'nzv_data/all'

   